const SUBJECT="MEFOS";const STORAGE_KEY="MEFOS_V1_BANK_20261006";const FIXED_BANK=window.MEFOS_FIXED_BANK||[];const TOPIC_LABELS={"1.5.1": "Tema 1.5.1 · Tronco del encéfalo", "1.5.2": "Tema 1.5.2 · Pares craneales", "1.6": "Tema 1.6 · Diencéfalo", "1.7": "Tema 1.7 · Telencéfalo", "1.8": "Tema 1.8 · Funciones cerebrales superiores", "1.9.1": "Tema 1.9.1 · Corteza motora y vías motoras descendentes", "1.9.2": "Tema 1.9.2 · Ganglios basales y circuitos del movimiento", "1.9.3": "Tema 1.9.3 · Cerebelo, microanatomía y coordinación", "1.10": "Tema 1.10 · Sistema somatosensorial, mecanorreceptores y dolor", "1.11.1": "Tema 1.11.1 · Sistema visual", "1.11.2": "Tema 1.11.2 · Sistema auditivo y vestibular", "1.11.3": "Tema 1.11.3 · Gusto y olfato", "1.12": "Tema 1.12 · Sistema nervioso autónomo (sna)", "1.2": "Tema 1.2 · Embriología del sistema nervioso", "1.3": "Tema 1.3 · Cubiertas, ventrículos, lcr y vascularización", "1.4": "Tema 1.4 · Médula espinal"};var bankEdited=false;
var reviewedReady=false;var latestImportIds=new Set();
function parseNumberedBank(text,filename){
let clean=text.replace(/\r/g,'').split('\n').filter(l=>!/^\s*(?:<PARSED TEXT|SIMULACRO\s*-|Página\s+\d+\s*$)/i.test(l)).join('\n');let split=clean.search(/^\s*GABARITO JUSTIFICADO\s*$/im);if(split<0)return [];let body=clean.slice(0,split),tail=clean.slice(split),keys={};let km=[...tail.matchAll(/^\s*(\d+)\.\s*([^\n]+)\s*$/gm)];km.forEach((m,i)=>{let letter=m[2].split(/[—–]/).at(-1).trim().match(/^([A-H])\*?$/i);keys[Number(m[1])]={answer:letter?letter[1].toUpperCase().charCodeAt(0)-65:null,explanation:tail.slice(m.index+m[0].length,km[i+1]?.index??tail.length).replace(/\[Página \d+\]/g,'').trim(),reviewNote:letter?'':'Respuesta del documento original por recuperar'}});let marks=[...body.matchAll(/^\s*Pregunta\s+(\d+)\s*$/gm)];return marks.map((m,i)=>{let chunk=body.slice(m.index+m[0].length,marks[i+1]?.index??body.length).split(/Respuesta\s*:/i)[0].replace(/\[Página \d+\]/g,'').trim(),opts=(()=>{let v=[...chunk.matchAll(/^\s*([A-H])\)\s*/gm)];return v.length>=2?v:[...chunk.matchAll(/([A-H])\)\s*/g)]})(),prev=body.slice(0,m.index),source=prev.slice(prev.lastIndexOf('Fuente:')+7).replace(/\[Página \d+\]/g,'').trim(),k=keys[Number(m[1])];return {id:'review-'+filename+'-'+m[1],number:m[1],statement:chunk.slice(0,opts[0]?.index??chunk.length).trim(),options:opts.map((o,j)=>chunk.slice(o.index+o[0].length,opts[j+1]?.index??chunk.length).trim()),answer:k?.answer??null,explanation:k?.explanation||'',reviewNote:k?.reviewNote||'',hack:'',subject:'MEFOS',source:filename+' · Pregunta '+m[1]+' · Fuente original: '+source}}).filter(q=>q.options.length>=2)}
function parseSemio(text,filename){
const clean=text.replace(/\f/g,'\n').split('\n').filter(l=>!/^\s*Tema 8 ·.*Pág\./.test(l)).join('\n');
const keys={};const km=[...clean.matchAll(/^\s*Gabarito\s*[-–—]\s*Pregunta\s+(complementaria\s+)?(\d+)\s*·\s*Respuesta correcta:\s*([A-H])[^\n]*$/gim)];
km.forEach((m,i)=>{let exp=clean.slice(m.index+m[0].length,km[i+1]?.index??clean.length).split(/^\s*(?:GABARITO COMENTADO|PARTE V|Solucionario del Caso|FLASHCARDS)/im)[0].replace(/\[Página \d+\]/g,'').trim();keys[(m[1]?'c':'p')+m[2]]={answer:m[3].toUpperCase().charCodeAt(0)-65,explanation:exp}});
const marks=[...clean.matchAll(/^\s*Pregunta\s+(complementaria\s+)?(\d+)\s*$/gim)];return marks.map((m,i)=>{let body=clean.slice(m.index+m[0].length,marks[i+1]?.index??clean.length).split(/^\s*(?:PARTE\s+[IVX]+\s*·|BLOQUE \d+|CASO CLÍNICO|GABARITO)/im)[0].replace(/\[Página \d+\]/g,'').trim();let opts=[...body.matchAll(/^\s*([A-H])\)\s*/gm)],k=keys[(m[1]?'c':'p')+m[2]],page=[...clean.slice(0,m.index).matchAll(/\[Página (\d+)\]/g)].at(-1)?.[1];return {id:'semio8-'+(m[1]?'c':'p')+m[2]+'-'+Date.now(),number:(m[1]?'Complementaria ':'')+m[2],statement:body.slice(0,opts[0]?.index??body.length).trim(),options:opts.map((o,j)=>body.slice(o.index+o[0].length,opts[j+1]?.index??body.length).trim()),answer:k?.answer??null,explanation:k?.explanation||'',hack:'',subject:'Semiología',source:filename+(page?' · página '+page:'')+' · '+(m[1]?'Complementaria ':'Pregunta ')+m[2]}}).filter(q=>q.options.length>=2);
}
function parseItemPDF(text,filename){
 let clean=text.replace(/\r/g,'').split('\n').filter(l=>!/^\s*(?:SIMULACRO\s*-|Página\s+\d+\s*$)/i.test(l)).join('\n');
 let split=clean.search(/^\s*GABARITO JUSTIFICADO\s*$/im);let questions=split>=0?clean.slice(0,split):clean,solutions=split>=0?clean.slice(split):'';
 let keys={};let matches=[...solutions.matchAll(/^\s*(\d+)\.\s*(Pregunta[^\n]*?)\s*[—–]\s*([^\n]+)\s*$/gm)];
 for(let i=0;i<matches.length;i++){let m=matches[i],body=solutions.slice(m.index+m[0].length,matches[i+1]?.index??solutions.length).replace(/\[Página \d+\]/g,'').split(/Nota de control:/i)[0].trim();keys[Number(m[1])]={label:m[3].trim(),explanation:body}}
 let marks=[...questions.matchAll(/^\s*[ÍI]tem\s+(\d+)\s*\|\s*([^\n]+)\n/gm)],out=[];
 for(let i=0;i<marks.length;i++){let m=marks[i],body=questions.slice(m.index+m[0].length,marks[i+1]?.index??questions.length);body=body.split(/Respuesta\s*:/i)[0].replace(/\[Página \d+\]/g,'').trim();let opts=[...body.matchAll(/^\s*([A-H])\)\s*/gm)];if(opts.length<2)continue;let k=keys[Number(m[1])],keyLabel=k?.label.split(/[—–]/).at(-1).trim(),letter=keyLabel?.match(/^([A-H])\s*\*?\s*$/i)?.[1]?.toUpperCase();let page=[...questions.slice(0,m.index).matchAll(/\[Página (\d+)\]/g)].at(-1)?.[1]||[...text.slice(0,text.indexOf(m[0])).matchAll(/Página\s+(\d+)/g)].at(-1)?.[1]||'no detectada';out.push({id:'item-'+Date.now()+'-'+m[1],number:m[1],statement:body.slice(0,opts[0].index).trim(),options:opts.map((o,j)=>body.slice(o.index+o[0].length,opts[j+1]?.index??body.length).trim()),answer:letter?opts.findIndex(o=>o[1]===letter):null,explanation:k?.explanation||'',hack:'',source:filename+' · página '+page+' · Ítem '+m[1]+' · '+m[2].trim(),reviewNote:letter?'':k?.label||'Sin respuesta detectada'})}
 return out;
}

const $=id=>document.getElementById(id);let bank=[],wrong=new Set(),session=null,ticker;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function loadBankSafe(){
  const fixed=structuredClone(FIXED_BANK);
  try{
    const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');
    wrong=new Set(x.wrong||[]);
    const extras=Array.isArray(x.extra)?x.extra:[];
    const edited=Array.isArray(x.editedBank)?x.editedBank:[];
    // Nunca permitir que un estado local viejo/vacío sustituya el banco canónico incorporado.
    const byId=new Map(fixed.map(q=>[q.id,q]));
    for(const q of edited){ if(q&&q.id&&byId.has(q.id)) byId.set(q.id,q); }
    for(const q of extras){ if(q&&q.id&&!byId.has(q.id)) byId.set(q.id,q); }
    bank=[...byId.values()];
    bankEdited=edited.length>0;
  }catch(e){
    bank=fixed;
    wrong=new Set();
    bankEdited=false;
  }
}
loadBankSafe();
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({wrong:[...wrong],extra:bank.filter(q=>!q.id.startsWith("neuro20261004-")),...(bankEdited?{editedBank:bank}:{})}))}catch{$('status').textContent='Almacenamiento local no disponible. Exporta el banco para conservarlo.'}}
function valid(q){return q&&typeof q.statement==='string'&&q.statement.trim()&&Array.isArray(q.options)&&q.options.length>=2&&q.options.length<=8&&q.options.every(o=>typeof o==='string'&&o.trim())&&Number.isInteger(q.answer)&&q.answer>=0&&q.answer<q.options.length}
function refresh(){if($('openwrong'))$('openwrong').textContent='Banco de fallos ('+bank.filter(q=>valid(q)&&wrong.has(q.id)).length+')';syncSelection();renderExamBuilder();bank.forEach((q,i)=>q.id=q.id||'q'+Date.now()+'-'+i);$('bankinfo').textContent=`${bank.filter(valid).length} preguntas disponibles para practicar`; $('reviewcount').textContent=`Revisión del banco (${bank.filter(q=>!valid(q)).length})`; $('wrongcount').textContent=`${wrong.size} preguntas en el historial de fallos`;$('editor').value=JSON.stringify(bank,null,2);$('pending').innerHTML=bank.filter(q=>!valid(q)).map(q=>'<details><summary>Ítem '+esc(q.number||'?')+' · '+esc(q.reviewNote||(q.answer===null||q.answer===undefined||q.answer<0?'Respuesta correcta no identificada':'Revisar enunciado, opciones o respuesta'))+'</summary><p>'+esc(q.statement)+'</p>'+q.options.map((o,i)=>'<p>'+String.fromCharCode(65+i)+') '+esc(o)+'</p>').join('')+'<p class=source>'+esc(q.source)+'</p><p class=feedback>'+esc(q.explanation||'Sin explicación')+'</p></details>').join('');save()}

function parseStructured(text,filename){
 text=text.replace(/\r/g,'').replace(/^\uFEFF/,'');
 if(!/^\s*Respuesta correcta:\s*[A-H]\b/im.test(text))return null;
 let marks=[...text.matchAll(/^\s*(\d+(?:\.\d+)*)\.\s+(?=\S)/gm)],out=[];
 for(let i=0;i<marks.length;i++){
 let m=marks[i],body=text.slice(m.index+m[0].length,marks[i+1]?.index??text.length).trim();
 let fm=[...body.matchAll(/^[ \t]*(Respuesta correcta|Explicación|Justificación|Justificación de las alternativas|Análisis de las alternativas|Hack|Fuente):[ \t]*/gm)];if(!fm.length)continue;let fields={};fm.forEach((f,j)=>fields[f[1]]=body.slice(f.index+f[0].length,fm[j+1]?.index??body.length).trim());
 let main=body.slice(0,fm[0].index),opts=[...main.matchAll(/^[ \t]*([A-H])\)[ \t]*/gim)];if(opts.length<2)continue;
 let key=fields['Respuesta correcta']?.match(/^([A-H])\b/i)?.[1]?.toUpperCase();let q={id:'txt-'+Date.now()+'-'+i,number:m[1],statement:main.slice(0,opts[0].index).trim(),options:opts.map((o,j)=>main.slice(o.index+o[0].length,opts[j+1]?.index??main.length).trim()),answer:key?opts.findIndex(o=>o[1].toUpperCase()===key):null,explanation:['Explicación','Justificación','Justificación de las alternativas','Análisis de las alternativas'].filter(k=>fields[k]).map(k=>fields[k]).join('\n\n'),hack:fields.Hack||'',source:fields.Fuente||filename,document:filename,subject:SUBJECT};q.topic=topicOf(q);out.push(q);
 }return out.length?out:null;
}

var lastParseIssue='';
function parse(text,filename='Texto pegado'){
lastParseIssue='';
if(isCorrectionOnly(text)){lastParseIssue='Este archivo contiene un solucionario, sin los enunciados y las alternativas originales. Sube también el simulacro de preguntas; los apartados «Distractores» son explicaciones, no opciones de respuesta. No se han añadido preguntas.';return []}

text=text.replace(/\r/g,'').replace(/\u00a0/g,' ').replace(/^([ \t]*)\*\*([^\n]*?)\*\*([ \t]*:?)/gm,'$1$2$3').replace(/^\s*#{1,6}\s*/gm,'').replace(/^[ \t]*[-•]\s*(?=[A-Ha-h][).])/gm,'').replace(/^(?:Pregunta|Questão)\s+(\d+(?:\.\d+)*)\s*[:.)-]?\s*/gim,'$1. ').replace(/^[ \t]*([a-hA-H])\.\s+/gm,'$1) ');

const structured=parseStructured(text,filename);if(structured!==null)return structured;
if(/^\s*Pregunta\s+\d+\s*$/m.test(text)&&/^\s*GABARITO JUSTIFICADO\s*$/im.test(text))return parseNumberedBank(text,filename);
if(/^\s*Gabarito\s*[-–—]\s*Pregunta\s+(?:complementaria\s+)?\d+\s*·\s*Respuesta correcta:/im.test(text))return parseSemio(text,filename);
 if(/^\s*[ÍI]tem\s+\d+\s*\|/im.test(text))return parseItemPDF(text,filename);
 text=text.replace(/\r/g,'').replace(/\u00a0/g,' ');let keys={};let keypart=text.split(/(?:GABARITO|SOLUCIONARIO|CLAVE DE RESPUESTAS|RESPUESTAS CORRECTAS)\s*[:\n]/i);if(keypart.length>1){let tail=keypart.slice(1).join('\n');for(let m of tail.matchAll(/(?:^|\n|\s)(\d+)\s*[.):-]\s*([a-h])\b/gi))keys[m[1]]=m[2].toLowerCase();text=keypart[0]}
 const start=/^\s*(?:(?:pregunta|quest[aã]o)\s*(\d+)\s*[:.)-]|(\d+)\s*[.)-]\s+|Quest[aã]o e Alternativas\s*:)/gim;let marks=[...text.matchAll(start)];let chunks=marks.map((m,i)=>({num:m[1]||m[2]||String(i+1),body:text.slice(m.index+m[0].length,marks[i+1]?.index??text.length),offset:m.index}));if(!chunks.length&&/[aA]\s*[).]/.test(text))chunks=[{num:'1',body:text,offset:0}];let out=[];
 for(let c of chunks){let body=c.body.replace(/\[Página \d+\]/g,'');let am=body.match(/(?:alternativa\s+corre(?:cta|ta)|respuesta\s+correcta|soluci[oó]n|correcta)\s*[:：]\s*\(?([a-h])\b/i);let answer=am?am[1].toLowerCase():keys[c.num];let exp=body.match(/(?:explicaci[oó]n|explica[cç][aã]o|justificaci[oó]n)\s*:\s*([\s\S]*?)(?=\n\s*(?:hack|fuente|fonte)|$)/i)?.[1]?.trim()||'';let hack=body.match(/hack(?:\s*\/[^:\n]*)?\s*:\s*([\s\S]*?)(?=\n\s*(?:fuente|fonte)|$)/i)?.[1]?.trim()||'';
 let correctText=body.match(/(?:alternativa\s+corre(?:cta|ta)|respuesta\s+correcta)\s*:\s*([\s\S]*?)(?=\n\s*(?:hack|explic|fuente|fonte)|$)/i)?.[1]?.trim()||'';if(!exp&&correctText)exp=correctText;
 let original=body.match(/(?:fuente|fonte)\s*:\s*([^\n]+)/i)?.[1]||'';
 let main=body.split(/(?:alternativa\s+corre(?:cta|ta)|respuesta\s+correcta|explicaci[oó]n|explica[cç][aã]o|hack(?:\s*\/[^:\n]*)?)\s*:/i)[0];let opts=[...main.matchAll(/(?:^|\s)([a-hA-H])\s*[).]\s+/g)];if(opts.length<2)continue;let statement=main.slice(0,opts[0].index).trim();let options=opts.map((m,i)=>main.slice(m.index+m[0].length,opts[i+1]?.index??main.length).trim());let page=[...text.slice(0,c.offset).matchAll(/\[Página (\d+)\]/g)].at(-1)?.[1]||'1';out.push({id:'q'+Date.now()+'-'+out.length,number:c.num,statement,options,answer:answer?opts.findIndex(m=>m[1].toLowerCase()===answer):null,explanation:exp,hack,source:[original,filename+' · página '+page].filter(Boolean).join(' — ')})}return out;
}
async function pdfText(file){let doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer()),useSystemFonts:true}).promise;let text='';for(let n=1;n<=doc.numPages;n++){$('status').textContent=`Leyendo ${file.name}: página ${n}/${doc.numPages}`;let content=await(await doc.getPage(n)).getTextContent();let lines=[];for(let item of content.items){if(!('str'in item)||!item.str.trim())continue;let y=item.transform[5],line=lines.find(l=>Math.abs(l.y-y)<3);if(!line){line={y,items:[]};lines.push(line)}line.items.push(item)}lines.sort((a,b)=>b.y-a.y);text+=`\n[Página ${n}]\n`+lines.map(l=>l.items.sort((a,b)=>a.transform[4]-b.transform[4]).map(i=>i.str).join(' ')).join('\n')+'\n'}await doc.destroy();return text}
$('files').onchange=async e=>{let total=0;latestImportIds=new Set();try{for(let f of e.target.files){let data;if(f.name.toLowerCase().endsWith('.json')){let obj=JSON.parse(await f.text());data=Array.isArray(obj)?obj:obj.bank;if(!Array.isArray(data))throw Error('JSON: debe contener un banco de preguntas');if(obj.wrong)for(let id of obj.wrong)wrong.add(id)}else{let text=f.name.toLowerCase().endsWith('.pdf')?await pdfText(f):await f.text();data=parse(text,f.name);if(!data.length){$('paste').value=text;switchInput(true);$('pastestatus').textContent=lastParseIssue||'No se reconoció la estructura. El texto extraído está aquí para revisarlo o completarlo.';throw Error(lastParseIssue||'No se han detectado preguntas en '+f.name+'. Si es un escaneado, convierte antes el documento mediante OCR. También puedes pegar texto.')}}data=data.map(q=>({...q,document:f.name,topic:topicOf(q,f.name)}));for(const id of addQuestions(data))latestImportIds.add(id);total+=data.length}selectImported();refresh();$('status').textContent=`Importadas ${total} preguntas. Revisa el banco antes de comenzar: el formato de los PDF puede variar.`}catch(err){refresh();$('status').textContent=err.message}e.target.value=''};
$('apply').onclick=()=>{try{let a=JSON.parse($('editor').value);if(!Array.isArray(a)||a.some(q=>!q||typeof q.statement!=='string'||!Array.isArray(q.options)))throw Error('Debe ser una lista de preguntas con statement y options.');bankEdited=true;bank=a.map(q=>({...q,subject:SUBJECT}));wrong=new Set([...wrong].filter(id=>bank.some(q=>q.id===id)));refresh();$('status').textContent='Cambios aplicados. answer usa índices: 0 = A, 1 = B, 2 = C, 3 = D; null = sin clave.'}catch(e){$('status').textContent='No se ha aplicado: '+e.message}};
$('export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({bank,wrong:[...wrong]},null,2)],{type:'application/json'}));a.download='Mi_banco_examenes.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('clear').onclick=()=>{if(confirm('¿Vaciar las preguntas importadas y el historial de fallos de MEFOS?')){bank=structuredClone(FIXED_BANK);bankEdited=false;wrong.clear();refresh()}};
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
$('start').onclick=()=>{if(hasSavedSession()&&!confirm('Hay una sesión guardada. ¿Sustituirla por una nueva?'))return;if($('mode').value==='custom'){startCustomExam();return}let mode=$('mode').value,qs=bank.filter(valid).filter(q=>$('subject').value==='all'||(q.subject||'MEFOS')===$('subject').value).filter(matchesTopic).filter(matchesDocument).filter(q=>mode!=='wrong'||wrong.has(q.id));let count=$('allquestions').checked?qs.length:+$('count').value,minutes=+$('minutes').value,penalty=$('scoring').value==='none'?0:+$('penalty').value;if(!Number.isInteger(count)||count<1||!Number.isFinite(minutes)||minutes<=0||!Number.isFinite(penalty)||penalty<0){alert('Comprueba la cantidad, el tiempo y la penalización.');return}if(!qs.length){alert(mode==='wrong'?'No hay errores guardados para repasar.':'Añade preguntas con una clave válida.');return}session={qs:($('order').value==='shuffle'?shuffle(qs.slice()):qs.slice()).slice(0,count),mode,penalty,answers:[],index:0,deadline:Date.now()+minutes*60000,started:Date.now(),done:false};$('setup').classList.add('hidden');$('result').classList.add('hidden');$('quiz').classList.remove('hidden');clearInterval(ticker);ticker=setInterval(tick,250);tick();render()};
function tick(){if(!session||session.done||session.paused)return;let seconds=Math.max(0,Math.ceil((session.deadline-Date.now())/1000));$('clock').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');if(!seconds)finish()}
function feedback(q,a){return (a===q.answer?'✓ Respuesta correcta.':'✗ Respuesta incorrecta.')+'\nCorrecta: '+String.fromCharCode(65+q.answer)+') '+q.options[q.answer]+(q.explanation?'\n\nExplicación: '+q.explanation:'')+(q.hack?'\n\nHack / trampa: '+q.hack:'')}
function render(){let s=session,q=s.qs[s.index],a=s.answers[s.index];$('copystatus').textContent='';$('position').textContent=`Pregunta ${s.index+1} de ${s.qs.length}`;$('progress').max=s.qs.length;$('progress').value=s.answers.filter(a=>a!==undefined).length;$('source').textContent='Fuente: '+(q.source||'No indicada en el documento');$('statement').textContent=q.statement;$('options').replaceChildren();q.options.forEach((o,i)=>{let b=document.createElement('button');b.className='option';b.textContent=String.fromCharCode(65+i)+') '+o;if(a!==undefined){if(s.mode==='exam'){if(a===i)b.classList.add('selected')}else{b.disabled=true;if(i===q.answer)b.classList.add('correct');else if(a===i)b.classList.add('wrong')}}b.onclick=()=>{if(s.done)return;s.answers[s.index]=i;if(s.mode==='exam'){advanceQuestion();return}if(s.mode!=='exam'){if(i!==q.answer)wrong.add(q.id);else wrong.delete(q.id);save()}render()};$('options').append(b)});$('feedback').classList.toggle('hidden',a===undefined||s.mode==='exam');$('feedback').textContent=a===undefined||s.mode==='exam'?'':feedback(q,a);$('prev').disabled=s.index===0;$('next').textContent=s.index===s.qs.length-1?'Ver pendientes':'Siguiente';$('finish').textContent=s.mode==='exam'?'Finalizar examen':'Finalizar sesión';renderQuestionMap()}
$('prev').onclick=()=>{if(session.index>0){session.index--;render()}};$('next').onclick=advanceQuestion;$('finish').onclick=()=>{let blanks=session.qs.reduce((n,q,i)=>n+(session.answers[i]===undefined),0);if(confirm('¿Finalizar y corregir? Quedan '+blanks+' preguntas en blanco.'))finish()};
function finish(){let s=session;if(!s||s.done)return;s.done=true;try{localStorage.removeItem(STORAGE_KEY+'_session')}catch{}clearInterval(ticker);let correct=0,errors=0,blank=0;s.qs.forEach((q,i)=>{let a=s.answers[i];if(a===undefined)blank++;else if(a===q.answer){correct++;wrong.delete(q.id)}else{errors++;wrong.add(q.id)}});save();let grade=Math.max(0,10*(correct-s.penalty*errors)/s.qs.length);$('quiz').classList.add('hidden');$('result').classList.remove('hidden');$('result').innerHTML=`<h2>Resultado: ${grade.toFixed(2)} / 10</h2><p>${correct} aciertos · ${errors} errores · ${blank} en blanco<br>${s.penalty===0?'Sin penalización':'Penalización: −'+s.penalty+' por error'} · Tiempo: ${Math.floor((Date.now()-s.started)/60000)} min</p><button id="again">Volver al inicio</button><button id="retry">Repasar errores</button><h2>Corrección completa</h2>`+s.qs.map((q,i)=>`<details><summary>${i+1}. ${s.answers[i]===undefined?'En blanco':s.answers[i]===q.answer?'✓ Correcta':'✗ Incorrecta'} — ${esc(q.statement.slice(0,100))}</summary><button class="secondary" data-copy-index="${i}">Copiar pregunta</button><p>${esc(q.statement)}</p><p class="source">${esc(q.source||'Fuente no indicada')}</p>${q.options.map((o,j)=>`<p>${j===q.answer?'✓ ':''}${String.fromCharCode(65+j)}) ${esc(o)}${s.answers[i]===j?' ← Tu respuesta':''}</p>`).join('')}<p class="feedback">${esc(q.explanation||'Sin explicación en el documento.')}<br>${esc(q.hack?'Hack: '+q.hack:'')}</p></details>`).join('');$('again').onclick=()=>{showResume();$('setup').classList.remove('hidden');$('result').classList.add('hidden');refresh()};$('retry').onclick=()=>{$('again').click();$('mode').value='wrong';$('start').click()}}
refresh();


$("scoring").onchange=()=>{$("penalty").disabled=$("scoring").value==="none"};

function questionForCopy(q){return q.statement+'\n\n'+q.options.map((o,i)=>String.fromCharCode(65+i)+') '+o).join('\n')+'\n\nFuente: '+(q.source||'No indicada');}
async function copyQuestion(q){let text=questionForCopy(q);try{if(!navigator.clipboard?.writeText)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(text);$('copystatus').textContent='Pregunta copiada';return true}catch{let area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.top='0';area.style.left='-9999px';document.body.append(area);area.focus();area.select();area.setSelectionRange(0,text.length);let ok=false;try{ok=document.execCommand('copy')}catch{}area.remove();if(ok){$('copystatus').textContent='Pregunta copiada';return true}$('copytext').value=text;$('copydialog').showModal();return false}}
$('copyquestion').onclick=()=>copyQuestion(session.qs[session.index]);
$('result').addEventListener('click',async e=>{let b=e.target.closest('[data-copy-index]');if(b){let ok=await copyQuestion(session.qs[Number(b.dataset.copyIndex)]);if(ok){b.textContent='Copiada ✓';setTimeout(()=>b.textContent='Copiar pregunta',1800)}}});
$('closecopy').onclick=()=>$('copydialog').close();$('selectcopy').onclick=()=>{$('copytext').focus();$('copytext').select();$('copytext').setSelectionRange(0,$('copytext').value.length)};


function switchInput(paste){$('filepanel').classList.toggle('hidden',paste);$('pastepanel').classList.toggle('hidden',!paste);$('tabfiles').setAttribute('aria-selected',String(!paste));$('tabpaste').setAttribute('aria-selected',String(paste));}
$('tabfiles').onclick=()=>switchInput(false);$('tabpaste').onclick=()=>switchInput(true);
let pasted=[];
$('parsepaste').onclick=()=>{pasted=parse($('paste').value);$('pastestatus').textContent=pasted.length?`Detectadas ${pasted.length} preguntas. Comprueba las respuestas y añade el test al banco.`:lastParseIssue||'No se han detectado preguntas. Usa un enunciado numerado seguido de A), B), C), D) y, si corresponde, E).';$('addpasted').classList.toggle('hidden',!pasted.length);$('pastepreview').innerHTML=pasted.map((q,i)=>`<details open><summary>Pregunta ${i+1}</summary><p>${esc(q.statement)}</p>${q.options.map((o,j)=>`<p>${String.fromCharCode(65+j)}) ${esc(o)}</p>`).join('')}<label>Respuesta correcta <select data-paste-answer="${i}"><option value="">Sin respuesta correcta identificada</option>${q.options.map((o,j)=>`<option value="${j}" ${q.answer===j?'selected':''}>${String.fromCharCode(65+j)}) ${esc(o)}</option>`).join('')}</select></label>${q.explanation?'<p class="feedback">'+esc(q.explanation)+'</p>':''}</details>`).join('');};
$('addpasted').onclick=()=>{if(!pasted.length)return;$('pastepreview').querySelectorAll('[data-paste-answer]').forEach(el=>{pasted[Number(el.dataset.pasteAnswer)].answer=el.value===''?null:Number(el.value)});let count=pasted.length,ready=pasted.filter(valid).length;latestImportIds=new Set(addQuestions(pasted.map(q=>({...q,document:'Texto pegado',topic:topicOf(q)}))));selectImported();pasted=[];refresh();$('addpasted').classList.add('hidden');$('pastestatus').textContent=`Añadidas ${count} preguntas; ${ready} listas para corregir. Elige el modo y pulsa Comenzar.`;$('status').textContent=$('pastestatus').textContent;};


function documentName(q){return q.document||(q.source||'Sin documento').split(' · ')[0]}
function syncSelection(){
 const topics=[...new Set(bank.map(topicOf))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));let old=$('topicfilter').value;
 $('topicfilter').innerHTML='<option value="all">Todos los temas (mezclar)</option>'+topics.map(t=>'<option value="'+esc(t)+'">'+esc(topicLabel(t))+'</option>').join('');$('topicfilter').value=topics.includes(old)||old==='all'?old:(topics.includes('1.2')?'1.2':topics[0]||'all');
 let list=bank.filter(matchesTopic),doc=$('documentfilter').value,names=[...new Set(list.map(documentName))];
 $('documentfilter').innerHTML='<option value="all">Todos los bancos/documentos de este tema</option>'+(latestImportIds.size?'<option value="__recent">Solo la última importación</option>':'')+names.map(n=>'<option value="'+esc(n)+'">'+esc(n)+'</option>').join('');$('documentfilter').value=names.includes(doc)||(doc==='__recent'&&latestImportIds.size)?doc:'all';
 $('topicnav').innerHTML=topics.map(t=>'<button type="button" class="topiccard '+($('topicfilter').value===t?'active':'')+'" data-topic="'+esc(t)+'"><strong>'+esc(topicLabel(t))+'</strong><span>'+bank.filter(q=>topicOf(q)===t&&valid(q)).length+' preguntas</span></button>').join('');syncCount();}
function syncCount(){if($('exambuilder'))$('exambuilder').classList.toggle('hidden',$('mode').value!=='custom');let n=bank.filter(valid).filter(q=>$('subject').value==='all'||(q.subject||'MEFOS')===$('subject').value).filter(matchesTopic).filter(matchesDocument).filter(q=>$('mode').value!=='wrong'||wrong.has(q.id)).length;$('count').disabled=$('allquestions').checked;$('count').max=n;$('selectioninfo').textContent=topicLabel($('topicfilter').value)+' · '+n+' preguntas seleccionadas'+($('documentfilter').value==='__recent'?' · última importación':'');if($('allquestions').checked)$('count').value=n;}
$('subject').onchange=syncSelection;$('scoring').onchange=()=>{const off=$('scoring').value==='none';$('penalty').disabled=off;$('penalty').style.opacity=off?'.45':'1';$('penalty').setAttribute('aria-disabled',off?'true':'false');};$('scoring').onchange();
$('documentfilter').onchange=syncCount;$('mode').onchange=syncCount;$('allquestions').onchange=syncCount;
syncSelection();

function fingerprint(q){return (q.statement+'|'+q.options.join('|')).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'')}
function addQuestions(items){let seen=new Map(bank.map(q=>[topicOf(q)+"|"+documentName(q)+"|"+fingerprint(q),q])),ids=[];for(let q of items){if(!q||typeof q.statement!=='string'||!Array.isArray(q.options))throw Error('Pregunta sin enunciado u opciones.');let key=topicOf(q)+"|"+documentName(q)+"|"+fingerprint(q),existing=seen.get(key);if(existing){ids.push(existing.id);continue}q={...q,id:q.id||'import-'+Date.now()+'-'+bank.length,subject:SUBJECT,topic:topicOf(q)};bank.push(q);seen.set(key,q);ids.push(q.id)}return ids}
$('dismissstatus').onclick=()=>{$('status').textContent='';$('pastestatus').textContent=''};
$('resetwrong').onclick=()=>{if(confirm('¿Borrar el historial de fallos de '+SUBJECT+'? Las preguntas se conservan.')){wrong.clear();refresh()}};
refresh();

function topicOf(q,filename=''){
 if(q.topic)return String(q.topic);
 const text=(q.source||'')+' '+filename;
 let m=text.match(/Tema[ _-]*(\d+)[._](\d+)(?:[._](\d+))?/i);
 return m?[m[1],m[2],m[3]].filter(Boolean).join('.'):'sin-clasificar';
}
function topicLabel(t){return TOPIC_LABELS[t]||({'all':'Todos los temas (mezclar)','sin-clasificar':'Sin tema identificado'})[t]||'Tema '+t}
function matchesTopic(q){return $('topicfilter').value==='all'||topicOf(q)===$('topicfilter').value}
function matchesDocument(q){let d=$('documentfilter').value;return d==='all'||(d==='__recent'?latestImportIds.has(q.id):documentName(q)===d)}
function selectImported(){let ts=[...new Set(bank.filter(q=>latestImportIds.has(q.id)).map(topicOf))];syncSelection();$('topicfilter').value=ts.length===1?ts[0]:'all';syncSelection();$('documentfilter').value='__recent';syncCount();}
$('topicfilter').onchange=()=>{$('documentfilter').value='all';syncSelection()};
$('topicnav').addEventListener('click',e=>{let b=e.target.closest('[data-topic]');if(b){$('topicfilter').value=b.dataset.topic;$('documentfilter').value='all';$('mode').value='random';syncSelection();$('sessionconfig').scrollIntoView({behavior:'smooth',block:'start'})}});

refresh();
function examKey(q){return (q.statement+'|'+q.options.join('|')).replace(/\s+/g,' ').trim().toLowerCase()}
function examPools(){let pools={};for(let q of bank.filter(valid)){let t=topicOf(q);if(!pools[t])pools[t]=new Map();let key=examKey(q);if(!pools[t].has(key))pools[t].set(key,q)}return pools}
function renderExamBuilder(){let pools=examPools(),old={};$('examrows').querySelectorAll('input[data-exam-topic]').forEach(x=>old[x.dataset.examTopic]=x.value);$('examrows').innerHTML=Object.keys(pools).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})).map(t=>'<label class="examrow"><span>'+esc(topicLabel(t))+'<small>'+pools[t].size+' preguntas distintas disponibles</small></span><input type="number" inputmode="numeric" min="0" max="'+pools[t].size+'" value="'+esc(old[t]||0)+'" data-exam-topic="'+esc(t)+'" aria-label="Cantidad de '+esc(topicLabel(t))+'"></label>').join('');updateExamTotal()}
function updateExamTotal(){let total=0;$('examrows').querySelectorAll('input[data-exam-topic]').forEach(x=>total+=Math.max(0,Number(x.value)||0));$('examtotal').textContent='Total del examen: '+total+' preguntas';}
// Assign unique questions to topic quotas using augmenting paths, so overlapping topics do not cause a greedy shortage.
function assembleExam(requests,randomize){let pools=examPools(),slots=[],owners=new Map(),assigned=[];for(const [t,n] of Object.entries(requests)){if(!Number.isInteger(n)||n<0||n>(pools[t]?.size||0))throw Error('Revisa la cantidad de '+topicLabel(t));let candidates=[...(pools[t]||new Map()).keys()];if(randomize)shuffle(candidates);for(let i=0;i<n;i++)slots.push({topic:t,candidates})}
 if(!slots.length)throw Error('Elige al menos una pregunta en el reparto por temas.');
 function assign(i,visited){for(const key of slots[i].candidates){if(visited.has(key))continue;visited.add(key);let old=owners.get(key);if(old===undefined||assign(old,visited)){owners.set(key,i);assigned[i]=key;return true}}return false}
 for(let i=0;i<slots.length;i++)if(!assign(i,new Set()))throw Error('Estos temas comparten preguntas. Reduce alguna cantidad: no hay suficientes preguntas distintas para cumplir este reparto sin repeticiones.');
 let result=slots.map((s,i)=>pools[s.topic].get(assigned[i]));if(randomize)return shuffle(result);return result.sort((a,b)=>topicOf(a).localeCompare(topicOf(b),undefined,{numeric:true})||Number(a.number)-Number(b.number));}
function startCustomExam(){try{let requests={};$('examrows').querySelectorAll('input[data-exam-topic]').forEach(x=>requests[x.dataset.examTopic]=Number(x.value));let minutes=Number($('minutes').value),penalty=$('scoring').value==='none'?0:Number($('penalty').value);if(!Number.isFinite(minutes)||minutes<=0||!Number.isFinite(penalty)||penalty<0)throw Error('Revisa el tiempo y la penalización.');let qs=assembleExam(requests,$('order').value==='shuffle');session={qs,mode:'exam',penalty,answers:[],index:0,deadline:Date.now()+minutes*60000,started:Date.now(),done:false,requests};$('setup').classList.add('hidden');$('result').classList.add('hidden');$('quiz').classList.remove('hidden');clearInterval(ticker);ticker=setInterval(tick,250);tick();render()}catch(e){$('examerror').textContent=e.message;$('examerror').scrollIntoView?.({block:'center',behavior:'smooth'})}}
$('examrows').addEventListener('input',()=>{$('examerror').textContent='';updateExamTotal()});
$('zeroexam').onclick=()=>{$('examrows').querySelectorAll('input[data-exam-topic]').forEach(x=>x.value=0);updateExamTotal()};

let studyScale=1;function applyStudyScale(){document.documentElement.style.setProperty('--study-font-scale',studyScale.toFixed(2));if($('fontreset'))$('fontreset').textContent=Math.round(studyScale*100)+'%';try{localStorage.setItem('mefos-v1-font-scale',String(studyScale))}catch{}}try{studyScale=Math.min(1.6,Math.max(.85,Number(localStorage.getItem('mefos-v1-font-scale'))||1))}catch{};applyStudyScale();$('fontminus').onclick=()=>{studyScale=Math.max(.85,studyScale-.1);applyStudyScale()};$('fontplus').onclick=()=>{studyScale=Math.min(1.6,studyScale+.1);applyStudyScale()};$('fontreset').onclick=()=>{studyScale=1;applyStudyScale()};
refresh();$('jumppractice').onclick=()=>{$('mode').value='random';syncCount();$('sessionconfig').scrollIntoView({behavior:'smooth',block:'start'})};
$('jumpexam').onclick=()=>{$('mode').value='custom';syncCount();$('sessionconfig').scrollIntoView({behavior:'smooth',block:'start'})};

function advanceQuestion(){if(!session||session.done)return;if(session.index<session.qs.length-1){session.index++;render();$('quiz').scrollIntoView?.({block:'start',behavior:'smooth'})}else{render();$('questionmap').open=true;renderQuestionMap();$('navnotice').textContent='Has llegado al final. Puedes revisar las pendientes o pulsar Finalizar examen.';}}
function renderQuestionMap(){let s=session;if(!s)return;persistSession();s.flags=s.flags||new Set();let blank=s.qs.reduce((n,q,i)=>n+(s.answers[i]===undefined),0),flagged=s.flags.size;$('maptitle').textContent=`Navegación · ${blank} en blanco · ${flagged} marcadas`;$('mapblank').textContent='En blanco / por hacer ('+blank+')';$('mapflag').textContent='Marcadas ('+flagged+')';let filter=s.mapFilter||'all';$('questionbuttons').innerHTML=s.qs.map((q,i)=>{let empty=s.answers[i]===undefined,flag=s.flags.has(i);if(filter==='blank'&&!empty||filter==='flag'&&!flag)return '';return '<button type="button" class="questionjump '+(i===s.index?'current ':'')+(empty?'unanswered':'answered')+'" data-go="'+i+'" aria-label="Pregunta '+(i+1)+(empty?', en blanco':', respondida')+(flag?', marcada':'')+'">'+(i+1)+(flag?' ★':'')+'</button>'}).join('')||'<p>No hay preguntas en este apartado.</p>';$('markreview').textContent=s.flags.has(s.index)?'★ Quitar marca':'☆ Marcar para revisar';$('clearanswer').disabled=s.mode!=='exam'||s.answers[s.index]===undefined;$('navnotice').textContent=s.mode==='exam'?'Examen: corrección únicamente al finalizar. Puedes volver y cambiar tus respuestas.':'Práctica: corrección inmediata al responder.';}
$('skip').onclick=advanceQuestion;
$('markreview').onclick=()=>{session.flags=session.flags||new Set();if(session.flags.has(session.index))session.flags.delete(session.index);else session.flags.add(session.index);renderQuestionMap()};
$('clearanswer').onclick=()=>{if(session.mode==='exam'){delete session.answers[session.index];render()}};
$('questionbuttons').addEventListener('click',e=>{let b=e.target.closest('[data-go]');if(!b)return;session.index=Number(b.dataset.go);render();$('quiz').scrollIntoView?.({block:'start',behavior:'smooth'})});
for(const [id,filter] of [['mapall','all'],['mapblank','blank'],['mapflag','flag']])$(id).onclick=()=>{session.mapFilter=filter;renderQuestionMap()};

function persistSession(){if(!session||session.done)return;try{localStorage.setItem(STORAGE_KEY+'_session',JSON.stringify({ids:session.qs.map(q=>q.id),answers:session.qs.map((q,i)=>session.answers[i]??null),index:session.index,mode:session.mode,penalty:session.penalty,flags:[...(session.flags||[])],mapFilter:session.mapFilter||'all',remaining:session.paused?session.remaining:Math.max(0,session.deadline-Date.now()),deadline:session.deadline,elapsed:session.paused?session.elapsed:Date.now()-session.started,paused:!!session.paused,savedAt:Date.now()}));}catch{$('navnotice').textContent='Este navegador no permite guardar la sesión. Mantén abierto el archivo para no perderla.'}}
function hasSavedSession(){try{return !!localStorage.getItem(STORAGE_KEY+'_session')}catch{return false}}
function showResume(){if($('openwrong'))$('openwrong').textContent='Banco de fallos ('+bank.filter(q=>valid(q)&&wrong.has(q.id)).length+')';let data;try{data=JSON.parse(localStorage.getItem(STORAGE_KEY+'_session')||'null')}catch{}$('resumebox').classList.toggle('hidden',!data);if(data)$('resumetext').textContent=`Sesión guardada · ${data.answers.filter(a=>a!==null).length}/${data.ids.length} respondidas · pregunta ${data.index+1}`;}
function pauseSession(){if(!session||session.done)return;session.remaining=Math.max(0,session.deadline-Date.now());session.elapsed=Date.now()-session.started;session.paused=true;clearInterval(ticker);persistSession();$('quiz').classList.add('hidden');$('setup').classList.remove('hidden');showResume()}
function resumeSession(){try{let d=JSON.parse(localStorage.getItem(STORAGE_KEY+'_session')||'null');if(!d)return;let lookup=new Map(bank.map(q=>[q.id,q])),qs=d.ids.map(id=>lookup.get(id));if(qs.some(q=>!q)){alert('Faltan preguntas de esta sesión. Importa de nuevo el banco exportado antes de continuar.');return}let remaining=d.paused||d.mode!=='exam'?d.remaining:Math.max(0,d.deadline-Date.now());session={qs,answers:d.answers.map(a=>a===null?undefined:a),index:d.index,mode:d.mode,penalty:d.penalty,flags:new Set(d.flags),mapFilter:d.mapFilter,deadline:Date.now()+remaining,started:Date.now()-d.elapsed,done:false,paused:false};$('setup').classList.add('hidden');$('result').classList.add('hidden');$('quiz').classList.remove('hidden');clearInterval(ticker);if(remaining<=0){finish();return}ticker=setInterval(tick,250);render();tick()}catch{alert('No se ha podido recuperar la sesión guardada.')}}
$('resume').onclick=resumeSession;$('pausequiz').onclick=pauseSession;
$('discardresume').onclick=()=>{if(confirm('¿Descartar la sesión pendiente? El banco de preguntas y los fallos se conservan.')){localStorage.removeItem(STORAGE_KEY+'_session');session=null;showResume()}};
$('openwrong').onclick=()=>{let n=bank.filter(q=>valid(q)&&wrong.has(q.id)).length;if(!n){alert('Todavía no hay preguntas falladas para repasar.');return}if($('scope'))$('scope').value='single';if($('mixedpanel'))$('mixedpanel').classList.add('hidden');$('topicfilter').value='all';$('documentfilter').value='all';$('mode').value='wrong';$('allquestions').checked=true;syncSelection();$('sessionconfig').scrollIntoView?.({behavior:'smooth',block:'start'})};
$('openpaste').onclick=()=>{switchInput(true);$('pastepanel').scrollIntoView?.({behavior:'smooth',block:'start'});$('paste').focus()};
$('openimport').onclick=()=>{switchInput(false);$('files').click()};
window.addEventListener('pagehide',persistSession);
window.addEventListener('beforeunload',persistSession);
showResume();

function isCorrectionOnly(text){
 const blocks=[...String(text).matchAll(/^\s*\d+\.\s*\[[^\n]*\]/gm)];
 if(!blocks.length)return false;
 return blocks.every((m,i)=>{let b=text.slice(m.index+m[0].length,blocks[i+1]?.index??text.length),key=b.search(/^\s*Correcta:\s*[A-H]\)/im);return key>=0&&/^\s*Distractores\b/im.test(b)&&!/^\s*[A-H]\)\s+/im.test(b.slice(0,key))});
}
